plugins {
	id 'java'
	id 'org.springframework.boot' version '3.3.2'
	id 'io.spring.dependency-management' version '1.1.6'
	id 'jacoco'
}

group = 'cl.hope'
version = '0.0.1'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(17)
	}
}

repositories {
	mavenCentral()
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-web'
	implementation 'org.springframework.boot:spring-boot-starter-validation'
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
	implementation 'org.springframework.boot:spring-boot-starter-actuator'

	compileOnly 'org.projectlombok:lombok'
	annotationProcessor 'org.projectlombok:lombok'

	implementation 'org.mapstruct:mapstruct:1.5.5.Final'
	annotationProcessor 'org.mapstruct:mapstruct-processor:1.5.5.Final'

	runtimeOnly 'com.h2database:h2'
	runtimeOnly 'org.postgresql:postgresql'

	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
	testCompileOnly 'org.projectlombok:lombok'
	testAnnotationProcessor 'org.projectlombok:lombok'
}

jacoco {
	toolVersion = "0.8.11"
}

tasks.named('test') {
	useJUnitPlatform()
	finalizedBy jacocoTestReport
}

jacocoTestReport {
	dependsOn test
	reports {
		xml.required = true
		html.required = true
	}
}

jacocoTestCoverageVerification {
	violationRules {
		rule {
			element = 'CLASS'
			limit {
				minimum = 1.00
			}
			excludes = [
				'cl.hope.HopeApplication',
				'cl.hope.controllers.dtos.*',
				'cl.hope.services.entities.*',
				'cl.hope.repositories.entities.*',
				'cl.hope.exceptions.ErrorResponse',
				'cl.hope.exceptions.ErrorResponse.ErrorResponseBuilder',
				'cl.hope.exceptions.ErrorResponse.FieldError',
				'cl.hope.exceptions.ErrorResponse.FieldError.FieldErrorBuilder',
				'cl.hope.mappers.HopeMapperImpl'
			]
		}
	}
}

tasks.named('check') {
	dependsOn jacocoTestCoverageVerification
}
