version: '3.8'

services:
  app:
    image: 'spring-hope:latest'
    build:
      context: .
    container_name: spring-hope
    depends_on:
      - db
  db:
    image: 'postgres:latest'
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    ports:
      - "5432:5432"