spring:
  application:
    name: hope
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
database:
  user: postgres
  password: admin
  url: jdbc:postgresql://localhost:5432/postgres