spring:
  application:
    name: hope
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  properties:
    jakarta.persistence.jdbc.url: jdbc:h2:mem:testdb
    hibernate.dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
server:
  error:
    include-message: always
    include-binding-errors: always
#database:
#  user: postgres
#  password: admin
#  url: jdbc:postgresql://localhost:5432/postgres