spring:
  application:
    name: hope
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        boot:
          allow_jdbc_metadata_access: false
database:
  user: postgres
  password: admin
  url: jdbc:postgresql://localhost:5432/postgres