spring:
  application:
    name: hope
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized
